// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACQoEXINdwRwuEFxUTOZ6eddmkAbhzSi0',
    appId: '1:270158493501:web:4df5a890b641a218c5b754',
    messagingSenderId: '270158493501',
    projectId: 'cadastro-clientes-final',
    authDomain: 'cadastro-clientes-final.firebaseapp.com',
    storageBucket: 'cadastro-clientes-final.firebasestorage.app',
    measurementId: 'G-FG4JQ900W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Q5IFXfC5Omi1TVMVSV_3TlyeJ7EJ_9Y',
    appId: '1:270158493501:android:b610c9a3c8b11af2c5b754',
    messagingSenderId: '270158493501',
    projectId: 'cadastro-clientes-final',
    storageBucket: 'cadastro-clientes-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfMXAxWCZkLh6tupVa8V-KFtA8VIbobH4',
    appId: '1:270158493501:ios:63628d484e7db687c5b754',
    messagingSenderId: '270158493501',
    projectId: 'cadastro-clientes-final',
    storageBucket: 'cadastro-clientes-final.firebasestorage.app',
    iosBundleId: 'com.example.cadastroClientesFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfMXAxWCZkLh6tupVa8V-KFtA8VIbobH4',
    appId: '1:270158493501:ios:63628d484e7db687c5b754',
    messagingSenderId: '270158493501',
    projectId: 'cadastro-clientes-final',
    storageBucket: 'cadastro-clientes-final.firebasestorage.app',
    iosBundleId: 'com.example.cadastroClientesFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACQoEXINdwRwuEFxUTOZ6eddmkAbhzSi0',
    appId: '1:270158493501:web:e77ea6b9c17f056bc5b754',
    messagingSenderId: '270158493501',
    projectId: 'cadastro-clientes-final',
    authDomain: 'cadastro-clientes-final.firebaseapp.com',
    storageBucket: 'cadastro-clientes-final.firebasestorage.app',
    measurementId: 'G-8T4RMFED6G',
  );
}
